# Generated by Django 5.0.7 on 2024-07-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_verification_code_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Geçersiz e-posta adresi'}, max_length=254, unique=True),
        ),
    ]
