# Generated by Django 5.0.7 on 2024-08-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('users', '0007_alter_customuser_name_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='users', to='exams.exam'),
        ),
    ]
