# Generated by Django 5.0.7 on 2024-08-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_exams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='class_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, '3. Sınıf'), (4, '4. Sınıf'), (5, '5. Sınıf'), (6, '6. Sınıf'), (7, '7. Sınıf'), (8, '8. Sınıf'), (9, '9. Sınıf'), (10, '10. Sınıf'), (11, '11. Sınıf'), (12, '12. Sınıf'), (13, 'Üniversite')], null=True),
        ),
    ]
