# Generated by Django 5.0.7 on 2024-08-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_options_customuser_class_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='class_year',
        ),
    ]
