# Generated by Django 5.0.7 on 2024-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_class_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Geçersiz e-posta adresi.'}, max_length=254, unique=True),
        ),
    ]
