# Generated by Django 5.0.7 on 2024-08-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='free_trial_uses',
        ),
    ]
