# Generated by Django 5.0.7 on 2024-08-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customuser_free_trial_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(6, '6. Sınıf'), (7, '7. Sınıf'), (8, '8. Sınıf'), (9, '9. Sınıf'), (10, '10. Sınıf'), (11, '11. Sınıf'), (12, '12. Sınıf'), (13, 'Üniversite')], null=True),
        ),
    ]
