# Generated by Django 5.0.7 on 2024-10-14 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_display_in_homepage'),
        ('users', '0016_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Katılma Tarihi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Geçersiz e-posta adresi.'}, max_length=254, unique=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='users', to='exams.exam', verbose_name='Sınavlar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(6, '6. Sınıf'), (7, '7. Sınıf'), (8, '8. Sınıf'), (9, '9. Sınıf'), (10, '10. Sınıf'), (11, '11. Sınıf'), (12, '12. Sınıf'), (13, 'Üniversite')], null=True, verbose_name='Sınıf'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Personel mi?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Doğrulandı mı?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Şifre Sıfırlama'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=50, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Profil Resmi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Abonelik Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Son Kullanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
