# Generated by Django 5.0.7 on 2025-04-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_date_joined_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_anonymous_user',
            field=models.BooleanField(default=False, verbose_name='Anonymous User'),
        ),
    ]
