# Generated by Django 5.0.7 on 2024-08-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examtype',
            options={'verbose_name': 'Sınav Adı', 'verbose_name_plural': 'Sınav Adları'},
        ),
        migrations.AlterModelOptions(
            name='examyear',
            options={'verbose_name': 'Sınav Yılı', 'verbose_name_plural': 'Sınav Yılları'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Ders', 'verbose_name_plural': 'Dersler'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Konu', 'verbose_name_plural': 'Konular'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subjects',
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='questions.subject'),
            preserve_default=False,
        ),
    ]
