# Generated by Django 5.0.7 on 2024-08-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_examtype_name_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='achievement_code',
        ),
        migrations.AddField(
            model_name='topic',
            name='achievement_code',
            field=models.CharField(default=12, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
