# Generated by Django 5.0.7 on 2024-08-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
