# Generated by Django 5.0.7 on 2024-08-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_examtype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_option',
            new_name='correct_answer',
        ),
    ]
