# Generated by Django 5.0.7 on 2024-09-02 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_reporttype_questionreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Soru Raporu', 'verbose_name_plural': 'Soru Raporları'},
        ),
        migrations.RenameField(
            model_name='questionreport',
            old_name='comment',
            new_name='resolution_notes',
        ),
        migrations.AlterUniqueTogether(
            name='questionreport',
            unique_together={('user', 'question', 'report_type')},
        ),
    ]
