# Generated by Django 5.0.7 on 2024-09-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_alter_questionreport_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionreport',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionreport',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='questionreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReportType',
        ),
        migrations.DeleteModel(
            name='QuestionReport',
        ),
    ]
