# Generated by Django 5.0.7 on 2024-09-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_question_difficulty_level_alter_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='achievement_code',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
