# Generated by Django 5.0.7 on 2024-10-14 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_alter_topic_achievement_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='exam_years',
            field=models.ManyToManyField(blank=True, related_name='exam_types', to='questions.examyear', verbose_name='Sınav Yılları'),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='examyear',
            name='year',
            field=models.PositiveIntegerField(unique=True, verbose_name='Yıl'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Doğru Cevap'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Zorluk Seviyesi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.examtype', verbose_name='Sınav Türü'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.examyear', verbose_name='Sınav Yılı'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Resim URL'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(verbose_name='Soru Numarası'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.subject', verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.topic', verbose_name='Konu'),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_solution_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Video Çözüm URL'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam_types',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='questions.examtype', verbose_name='Sınav Türleri'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='achievement_code',
            field=models.PositiveIntegerField(unique=True, verbose_name='Başarı Kodu'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='questions.subject', verbose_name='Ders'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('name', 'subject')},
        ),
    ]
