# Generated by Django 5.0.7 on 2024-10-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogmmateryal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsection',
            options={'verbose_name': 'Sınav Türü', 'verbose_name_plural': 'Sınav Türleri'},
        ),
        migrations.AlterModelOptions(
            name='examstructure',
            options={'verbose_name': 'Sınav Yapısı', 'verbose_name_plural': 'Sınav Yapıları'},
        ),
        migrations.AlterModelOptions(
            name='examsubject',
            options={'verbose_name': 'Sınav Konusu', 'verbose_name_plural': 'Sınav Konuları'},
        ),
    ]
