# Generated by Django 5.0.7 on 2025-04-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam_types', models.ManyToManyField(related_name='exam_sets', to='questions.examtype')),
                ('exam_years', models.ManyToManyField(related_name='exam_sets', to='questions.examyear')),
                ('subjects', models.ManyToManyField(blank=True, related_name='exam_sets', to='questions.subject')),
                ('topics', models.ManyToManyField(blank=True, related_name='exam_sets', to='questions.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
