# Generated by Django 5.0.7 on 2025-04-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sets', '0001_initial'),
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sınav Seti', 'verbose_name_plural': 'Sınav Setleri'},
        ),
        migrations.AlterField(
            model_name='examset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='exam_types',
            field=models.ManyToManyField(related_name='exam_sets', to='questions.examtype', verbose_name='Sınav Türleri'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='exam_years',
            field=models.ManyToManyField(related_name='exam_sets', to='questions.examyear', verbose_name='Sınav Yılları'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif Mi'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='exam_sets', to='questions.subject', verbose_name='Dersler'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='exam_sets', to='questions.topic', verbose_name='Konular'),
        ),
        migrations.AlterUniqueTogether(
            name='examset',
            unique_together={('name', 'created_at')},
        ),
    ]
