# Generated by Django 5.0.7 on 2025-04-20 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sets', '0002_alter_examset_options_alter_examset_created_at_and_more'),
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExamConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_configurations', to=settings.AUTH_USER_MODEL)),
                ('exam_types', models.ManyToManyField(blank=True, related_name='+', to='questions.examtype')),
                ('exam_years', models.ManyToManyField(blank=True, related_name='+', to='questions.examyear')),
                ('subjects', models.ManyToManyField(blank=True, related_name='+', to='questions.subject')),
                ('topics', models.ManyToManyField(blank=True, related_name='+', to='questions.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
