# Generated by Django 5.0.7 on 2025-04-29 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sets', '0003_userexamconfiguration'),
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSetDisplaySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_set_display_sets', to=settings.AUTH_USER_MODEL)),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_sets', to='exam_sets.examset')),
                ('exam_types', models.ManyToManyField(related_name='exam_set_display_sets', to='questions.examtype')),
                ('exam_years', models.ManyToManyField(related_name='exam_set_display_sets', to='questions.examyear')),
                ('questions', models.ManyToManyField(related_name='exam_set_display_sets', to='questions.question')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_set_display_sets', to='questions.subject')),
                ('topic', models.ManyToManyField(related_name='exam_set_display_sets', to='questions.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSetQuizGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_set_quiz_groups', to=settings.AUTH_USER_MODEL)),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_groups', to='exam_sets.examset')),
                ('exam_types', models.ManyToManyField(related_name='exam_set_quiz_groups', to='questions.examtype')),
                ('exam_years', models.ManyToManyField(related_name='exam_set_quiz_groups', to='questions.examyear')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_set_quiz_groups', to='questions.subject')),
                ('topic', models.ManyToManyField(related_name='exam_set_quiz_groups', to='questions.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSetQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(related_name='exam_set_quizzes', to='questions.question')),
                ('quiz_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='exam_sets.examsetquizgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
