# Generated by Django 5.0.7 on 2025-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sets', '0005_examsetdisplaysetattempt_and_more'),
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsetdisplayset',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='examsetquizgroup',
            name='subject',
        ),
        migrations.AddField(
            model_name='examsetdisplayset',
            name='subjects',
            field=models.ManyToManyField(related_name='exam_set_display_sets', to='questions.subject'),
        ),
        migrations.AddField(
            model_name='examsetquizgroup',
            name='subjects',
            field=models.ManyToManyField(related_name='exam_set_quiz_groups', to='questions.subject'),
        ),
    ]
