# Generated by Django 5.0.7 on 2025-05-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sets', '0006_remove_examsetdisplayset_subject_and_more'),
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examset',
            name='subjects',
        ),
        migrations.CreateModel(
            name='ExamSetSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_sets.examset')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.subject')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('exam_set', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='examset',
            name='ordered_subjects',
            field=models.ManyToManyField(related_name='ordered_exam_sets', through='exam_sets.ExamSetSubject', to='questions.subject', verbose_name='Sıralı Dersler'),
        ),
    ]
