# Generated by Django 5.0.7 on 2025-05-06 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sets', '0007_remove_examset_subjects_examsetsubject_and_more'),
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsetsubject',
            options={'ordering': ['order'], 'verbose_name': 'Sınav Seti Ders Sıralaması', 'verbose_name_plural': 'Sınav Seti Ders Sıralamaları'},
        ),
        migrations.AlterField(
            model_name='examsetsubject',
            name='exam_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_sets.examset', verbose_name='Sınav Seti'),
        ),
        migrations.AlterField(
            model_name='examsetsubject',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='examsetsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.subject', verbose_name='Ders'),
        ),
    ]
