# Generated by Django 5.0.7 on 2024-08-22 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('days', models.PositiveIntegerField()),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.TextField()),
                ('merchant_oid', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('successful', 'Successful'), ('denied', 'Denied')], default='ongoing', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_basket', models.TextField()),
                ('total_payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TL', max_length=3)),
                ('installment_info', models.CharField(max_length=255)),
                ('subscription_end_date_before_payment', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date_after_payment', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paytr.paymentplan')),
            ],
        ),
    ]
