# Generated by Django 5.0.7 on 2024-10-13 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Ödeme', 'verbose_name_plural': 'Ödemeler'},
        ),
        migrations.AlterModelOptions(
            name='paymentplan',
            options={'verbose_name': 'Ödeme Planı', 'verbose_name_plural': 'Ödeme Planları'},
        ),
    ]
