# Generated by Django 5.0.7 on 2024-10-14 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytr', '0002_alter_payment_options_alter_paymentplan_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='TL', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_info',
            field=models.CharField(max_length=255, verbose_name='Taksit Bilgisi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant_oid',
            field=models.CharField(max_length=20, unique=True, verbose_name='Eşşiz İşlem Numarası'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paytr.paymentplan', verbose_name='Ödeme Planı'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Devam Ediyor'), ('successful', 'Başarılı'), ('denied', 'Reddedildi')], default='ongoing', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription_end_date_after_payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Sonrası Abonelik Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription_end_date_before_payment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Öncesi Abonelik Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Ödeme Miktarı'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_address',
            field=models.TextField(verbose_name='Kullanıcı Adresi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_basket',
            field=models.TextField(verbose_name='Kullanıcı Sepeti'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_ip',
            field=models.GenericIPAddressField(verbose_name='Kullanıcı IP Adresi'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='days',
            field=models.PositiveIntegerField(help_text='Kullanıcıların abonelik süresinin uzatılacağı gün sayısı.', verbose_name='Gün Sayısı'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Toplam fiyat üzerinden yapılacak indirim. Girilmezse indirim yapılmaz.', max_digits=10, null=True, verbose_name='İndirim'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='final_price',
            field=models.DecimalField(decimal_places=2, help_text='Kullanıcıların ödeyeceği toplam ücret. İndirim miktarı bunu etkilemez. Son fiyat.', max_digits=10, verbose_name='Son Fiyat'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif Mi?'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Başlık'),
        ),
    ]
