# Generated by Django 5.0.7 on 2024-11-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytr', '0003_alter_payment_created_at_alter_payment_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='days',
            field=models.PositiveIntegerField(help_text='Kullanıcıların ödeme sonrası abonelik süresine eklenecek ekstra gün sayısı.', verbose_name='Gün Sayısı'),
        ),
    ]
