# Generated by Django 5.0.7 on 2024-08-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_active',
        ),
    ]
