# Generated by Django 5.0.7 on 2024-08-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_exam_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_major_exam',
            field=models.BooleanField(default=False),
        ),
    ]
