# Generated by Django 5.0.7 on 2024-08-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_is_major_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='display_in_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
