# Generated by Django 5.0.7 on 2024-09-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionreport',
            old_name='resolution_notes',
            new_name='report_detail',
        ),
    ]
