# Generated by Django 5.0.7 on 2024-10-14 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
        ('reports', '0002_rename_resolution_notes_questionreport_report_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='questionreport',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='questions.question', verbose_name='Soru'),
        ),
        migrations.AlterField(
            model_name='questionreport',
            name='report_detail',
            field=models.TextField(blank=True, null=True, verbose_name='Rapor Detayı'),
        ),
        migrations.AlterField(
            model_name='questionreport',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reports', to='reports.reporttype', verbose_name='Rapor Türü'),
        ),
        migrations.AlterField(
            model_name='questionreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='reporttype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Adı'),
        ),
    ]
