# Generated by Django 5.0.7 on 2024-08-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_question_exam_type_alter_question_exam_year_and_more'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgroup',
            name='exam_types',
            field=models.ManyToManyField(related_name='quiz_groups', to='questions.examtype'),
        ),
        migrations.AddField(
            model_name='quizgroup',
            name='exam_years',
            field=models.ManyToManyField(related_name='quiz_groups', to='questions.examyear'),
        ),
        migrations.AddField(
            model_name='quizgroup',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_groups', to='questions.subject'),
        ),
        migrations.AddField(
            model_name='quizgroup',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_groups', to='questions.topic'),
        ),
    ]
