# Generated by Django 5.0.7 on 2024-08-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quizgroup_options_quizattempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='incorrectquestion',
            name='user_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
