# Generated by Django 5.0.7 on 2024-08-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quizattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incorrectquestion',
            options={'ordering': ['-quiz_attempt__created_at']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
    ]
