# Generated by Django 5.0.7 on 2024-08-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_favoritequestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritequestion',
            options={'ordering': ['-created_at']},
        ),
    ]
