# Generated by Django 5.0.7 on 2024-08-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_favoritequestion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritequestion',
            name='question_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incorrectquestion',
            name='question_order',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
