# Generated by Django 5.0.7 on 2024-08-18 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_examtype_name'),
        ('quizzes', '0008_favoritequestion_question_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDisplaySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_sets', to=settings.AUTH_USER_MODEL)),
                ('exam_types', models.ManyToManyField(related_name='display_sets', to='questions.examtype')),
                ('exam_years', models.ManyToManyField(related_name='display_sets', to='questions.examyear')),
                ('questions', models.ManyToManyField(related_name='display_sets', to='questions.question')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_sets', to='questions.subject')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_sets', to='questions.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
