# Generated by Django 5.0.7 on 2024-08-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_questiondisplayset'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='unanswered_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
