# Generated by Django 5.0.7 on 2024-08-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_quizattempt_unanswered_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='success_rate',
            field=models.FloatField(default=0),
        ),
    ]
