# Generated by Django 5.0.7 on 2024-08-31 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_rename_correct_option_question_correct_answer'),
        ('quizzes', '0011_quizattempt_success_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritequestion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoritequestion',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_questions', to='quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='favoritequestion',
            name='quiz_attempt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_questions', to='quizzes.quizattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritequestion',
            unique_together={('user', 'question', 'quiz')},
        ),
    ]
