# Generated by Django 5.0.7 on 2024-08-31 21:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_rename_correct_option_question_correct_answer'),
        ('quizzes', '0012_alter_favoritequestion_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritequestion',
            unique_together={('user', 'question')},
        ),
    ]
