# Generated by Django 5.0.7 on 2025-04-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
        ('quizzes', '0013_alter_favoritequestion_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizgroup',
            name='topic',
        ),
        migrations.AddField(
            model_name='quizgroup',
            name='topic',
            field=models.ManyToManyField(related_name='quiz_groups', to='questions.topic'),
        ),
    ]
