# Generated by Django 5.0.7 on 2025-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
        ('quizzes', '0014_remove_quizgroup_topic_quizgroup_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondisplayset',
            name='topic',
        ),
        migrations.AddField(
            model_name='questiondisplayset',
            name='topic',
            field=models.ManyToManyField(related_name='display_sets', to='questions.topic'),
        ),
    ]
