# Generated by Django 5.0.7 on 2025-04-19 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
        ('quizzes', '0015_remove_questiondisplayset_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondisplayset',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='quizgroup',
            name='topic',
        ),
        migrations.AddField(
            model_name='questiondisplayset',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_sets', to='questions.topic'),
        ),
        migrations.AddField(
            model_name='quizgroup',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_groups', to='questions.topic'),
        ),
    ]
