# Generated by Django 5.0.7 on 2025-04-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
        ('quizzes', '0016_remove_questiondisplayset_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDisplaySetTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_display_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.questiondisplayset')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.topic')),
            ],
            options={
                'db_table': 'quizzes_questiondisplayset_topic',
            },
        ),
        migrations.AddField(
            model_name='questiondisplayset',
            name='topics',
            field=models.ManyToManyField(related_name='display_sets_m2m', through='quizzes.QuestionDisplaySetTopic', to='questions.topic'),
        ),
        migrations.CreateModel(
            name='QuizGroupTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizgroup')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.topic')),
            ],
            options={
                'db_table': 'quizzes_quizgroup_topic',
            },
        ),
        migrations.AddField(
            model_name='quizgroup',
            name='topics',
            field=models.ManyToManyField(related_name='quiz_groups_m2m', through='quizzes.QuizGroupTopic', to='questions.topic'),
        ),
    ]
