# Generated by Django 5.0.7 on 2025-04-20 13:18

from django.db import migrations

def copy_data(apps, schema_editor):
    QuizGroup = apps.get_model('quizzes', 'QuizGroup')
    QuestionDisplaySet = apps.get_model('quizzes', 'QuestionDisplaySet')
    QuizGroupTopic = apps.get_model('quizzes', 'QuizGroupTopic')
    QuestionDisplaySetTopic = apps.get_model('quizzes', 'QuestionDisplaySetTopic')

    # Copy QuizGroup data
    for group in QuizGroup.objects.all():
        if group.topic_id:
            QuizGroupTopic.objects.create(
                quiz_group=group,
                topic_id=group.topic_id
            )

    # Copy QuestionDisplaySet data
    for display_set in QuestionDisplaySet.objects.all():
        if display_set.topic_id:
            QuestionDisplaySetTopic.objects.create(
                question_display_set=display_set,
                topic_id=display_set.topic_id
            )


class Migration(migrations.Migration):
    dependencies = [
        ('quizzes', '0017_add_topics_m2m_and_through_models'),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]
