# Generated by Django 5.0.7 on 2025-04-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0018_copy_topic_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondisplayset',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='quizgroup',
            name='topic',
        ),
    ]
