# Generated by Django 5.0.7 on 2025-04-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0019_remove_topic_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiondisplayset',
            old_name='topics',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='quizgroup',
            old_name='topics',
            new_name='topic',
        ),
    ]
