# Generated by Django 5.0.7 on 2025-04-20 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_rename_m2m_field_to_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondisplaysettopic',
            name='question_display_set',
            field=models.ForeignKey(db_column='questiondisplayset_id', on_delete=django.db.models.deletion.CASCADE, to='quizzes.questiondisplayset'),
        ),
        migrations.AlterField(
            model_name='quizgrouptopic',
            name='quiz_group',
            field=models.ForeignKey(db_column='quizgroup_id', on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizgroup'),
        ),
    ]
