# Generated by Django 5.0.7 on 2025-04-20 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_alter_questiondisplaysettopic_question_display_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondisplaysettopic',
            name='question_display_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.questiondisplayset'),
        ),
        migrations.AlterField(
            model_name='quizgrouptopic',
            name='quiz_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizgroup'),
        ),
    ]
