# Generated by Django 5.0.7 on 2025-04-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
        ('quizzes', '0022_alter_questiondisplaysettopic_question_display_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='motivational_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MotivationalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_rate_range', models.IntegerField(choices=[(1, '0-20%'), (2, '20-40%'), (3, '40-60%'), (4, '60-80%'), (5, '80-100%')])),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motivational_messages', to='questions.subject')),
            ],
            options={
                'ordering': ['success_rate_range', 'subject'],
            },
        ),
    ]
