# Generated by Django 5.0.7 on 2025-04-21 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
        ('quizzes', '0023_quizattempt_motivational_message_motivationalmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivationalmessage',
            options={'ordering': ['success_rate_range', 'subject'], 'verbose_name': 'Motivasyon Mesajı', 'verbose_name_plural': 'Motivasyon Mesajları'},
        ),
        migrations.AlterField(
            model_name='motivationalmessage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='motivationalmessage',
            name='message',
            field=models.TextField(verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='motivationalmessage',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motivational_messages', to='questions.subject', verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='motivationalmessage',
            name='success_rate_range',
            field=models.IntegerField(choices=[(1, '%0-20'), (2, '%20-40'), (3, '%40-60'), (4, '%60-80'), (5, '%80-100')], verbose_name='Başarı Oranı Aralığı'),
        ),
    ]
