# Generated by Django 5.0.7 on 2025-05-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0025_displaysetattempt_displaysetincorrectquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSubjectMotivationalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_rate_range', models.IntegerField(choices=[(1, '%0-20'), (2, '%20-40'), (3, '%40-60'), (4, '%60-80'), (5, '%80-100')], verbose_name='Başarı Oranı Aralığı')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Çoklu Ders Motivasyon Mesajı',
                'verbose_name_plural': 'Çoklu Ders Motivasyon Mesajları',
                'ordering': ['success_rate_range'],
            },
        ),
    ]
