# Generated by Django 5.0.7 on 2025-04-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectperformance',
            name='correct_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='incorrect_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='unanswered_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subjectperformance',
            name='unseen_percentage',
            field=models.FloatField(default=0),
        ),
    ]
