# Generated by Django 5.0.7 on 2025-04-26 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_metrics', '0002_subjectperformance_correct_percentage_and_more'),
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectperformance',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='questions.examtype'),
        ),
    ]
