# Generated by Django 5.0.7 on 2024-11-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0015_alter_examtype_exam_years_alter_examtype_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_data', models.JSONField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_histories', to='questions.topic')),
            ],
            options={
                'verbose_name': 'Konu Geçmişi',
                'verbose_name_plural': 'Konu Geçmişleri',
            },
        ),
    ]
