# Generated by Django 5.0.7 on 2024-10-07 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Sınav Yılı',
                'verbose_name_plural': 'Sınav Yılları',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Bölüm',
                'verbose_name_plural': 'Bölümler',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Üniversite',
                'verbose_name_plural': 'Üniversiteler',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('min_score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('program_code', models.PositiveIntegerField(blank=True, null=True)),
                ('program_type', models.CharField(blank=True, max_length=255, null=True)),
                ('education_length', models.PositiveIntegerField(blank=True, null=True)),
                ('exam_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_year', to='uni_rankings.examyear')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major', to='uni_rankings.major')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='uni_rankings.university')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programlar',
            },
        ),
    ]
