# Generated by Django 5.0.7 on 2024-10-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_rankings', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='uni_rankings.location'),
        ),
    ]
