# Generated by Django 5.0.7 on 2024-10-08 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_rankings', '0003_program_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='exam_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='uni_rankings.examyear'),
        ),
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='uni_rankings.location'),
        ),
        migrations.AlterField(
            model_name='program',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='uni_rankings.major'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='uni_rankings.university'),
        ),
    ]
