# Generated by Django 5.0.7 on 2024-10-14 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_rankings', '0004_alter_program_exam_year_alter_program_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examyear',
            name='year',
            field=models.PositiveIntegerField(unique=True, verbose_name='Yıl'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Konum Adı'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Bölüm Adı'),
        ),
        migrations.AlterField(
            model_name='program',
            name='education_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Eğitim Süresi'),
        ),
        migrations.AlterField(
            model_name='program',
            name='exam_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='uni_rankings.examyear', verbose_name='Sınav Yılı'),
        ),
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='uni_rankings.location', verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='program',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='uni_rankings.major', verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='program',
            name='max_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Maksimum Puan'),
        ),
        migrations.AlterField(
            model_name='program',
            name='min_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Minimum Puan'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Program Kodu'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Program Türü'),
        ),
        migrations.AlterField(
            model_name='program',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='uni_rankings.university', verbose_name='Üniversite'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Üniversite Adı'),
        ),
    ]
