# Generated by Django 5.0.7 on 2024-10-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkuploadstatus',
            old_name='durum',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='bulkuploadstatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bulkuploadstatus',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bulkuploadstatus',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
