# Generated by Django 5.0.7 on 2024-10-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_rename_durum_bulkuploadstatus_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploadstatus',
            name='task_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
